plugins_dir:
  - _plugins_core
  - _plugins

api_header_key: 'x-api-key'
api_headerkey_value: 'too0nxJhq43nESW5cWdH13ZB2ZIsEuG1EXcpZeL1'


# Site settings
baseurl: ""
permalink: pretty
default_lang: 'en'
languages: ['en']


# Build settings
markdown: kramdown

exclude:
  - 'sitemap.json'

keep_files: ['assets']
rsync_copy: ['_assets']
